[build]
  command = "npm run build"
  publish = "dist" # or "build" depending on your project setup
  environment = { NODE_VERSION = "18" }

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173 # If using Vite or similar dev server

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
